package org.pastalab.fray.instrumentation.base

object RuntimeDescriptors {
  val runtimeMethodMap =
      mapOf(
          "resetAllDelegate" to "()V",
          "onThreadCreateDone" to "(Ljava/lang/Thread;)V",
          "onThreadStart" to "(Ljava/lang/Thread;)V",
          "onThreadStartDone" to "(Ljava/lang/Thread;)V",
          "onThreadEnd" to "()V",
          "onThreadRun" to "()V",
          "onLockTryLock" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onLockTryLockInterruptibly" to
              "(Ljava/util/concurrent/locks/Lock;JLjava/util/concurrent/TimeUnit;)J",
          "onLockTryLockInterruptiblyDone" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onLockTryLockDone" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onLockLock" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onLockLockDone" to "()V",
          "onLockUnlock" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onLockUnlockDone" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onLockNewCondition" to
              "(Ljava/util/concurrent/locks/Condition;Ljava/util/concurrent/locks/Lock;)V",
          "onObjectWait" to "(Ljava/lang/Object;J)V",
          "onObjectWaitDone" to "(Ljava/lang/Object;)V",
          "onObjectNotify" to "(Ljava/lang/Object;)V",
          "onObjectNotifyAll" to "(Ljava/lang/Object;)V",
          "onConditionAwait" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onConditionAwaitDone" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onConditionSignal" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onConditionSignalDone" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onConditionSignalAll" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onAtomicOperation" to "(Ljava/lang/Object;Lorg/pastalab/fray/runtime/MemoryOpType;)V",
          "onAtomicOperationDone" to "()V",
          "onArrayLoad" to "(Ljava/lang/Object;I)V",
          "onArrayStore" to "(Ljava/lang/Object;I)V",
          "onFieldRead" to
              "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V",
          "onFieldWrite" to
              "(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V",
          "onStaticFieldRead" to "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V",
          "onStaticFieldWrite" to "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V",
          "onMonitorEnter" to "(Ljava/lang/Object;)V",
          "onMonitorExit" to "(Ljava/lang/Object;)V",
          "onMonitorExitDone" to "(Ljava/lang/Object;)V",
          "onExit" to "(I)V",
          "onYield" to "()V",
          "onSkipScheduling" to "(Ljava/lang/String;)V",
          "onSkipPrimitive" to "(Ljava/lang/String;)V",
          "onSkipPrimitiveDone" to "(Ljava/lang/String;)V",
          "onSkipSchedulingDone" to "(Ljava/lang/String;)V",
          "start" to "()V",
          "onMainExit" to "()V",
          "onThreadPark" to "()V",
          "onUnsafeThreadParkTimed" to "(ZJ)V",
          "onThreadParkDone" to "()V",
          "onThreadUnpark" to "(Ljava/lang/Thread;)V",
          "onThreadUnparkDone" to "(Ljava/lang/Thread;)V",
          "onThreadInterrupt" to "(Ljava/lang/Thread;)V",
          "onThreadInterruptDone" to "(Ljava/lang/Thread;)V",
          "onThreadGetState" to
              "(Ljava/lang/Thread\$State;Ljava/lang/Thread;)Ljava/lang/Thread\$State;",
          "onThreadGetAndClearInterrupt" to "(ZLjava/lang/Thread;)Z",
          "onThreadClearInterrupt" to "(Ljava/lang/Thread;)V",
          "onReentrantReadWriteLockInit" to
              "(Ljava/util/concurrent/locks/ReentrantReadWriteLock;)V",
          "onSemaphoreInit" to "(Ljava/util/concurrent/Semaphore;)V",
          "onSemaphoreAcquirePermits" to "(Ljava/util/concurrent/Semaphore;I)V",
          "onSemaphoreAcquire" to "(Ljava/util/concurrent/Semaphore;)V",
          "onSemaphoreTryAcquire" to "(Ljava/util/concurrent/Semaphore;)V",
          "onSemaphoreTryAcquirePermits" to "(Ljava/util/concurrent/Semaphore;I)V",
          "onSemaphoreTryAcquirePermitsTimeout" to
              "(Ljava/util/concurrent/Semaphore;IJLjava/util/concurrent/TimeUnit;)J",
          "onSemaphoreTryAcquireTimeout" to
              "(Ljava/util/concurrent/Semaphore;JLjava/util/concurrent/TimeUnit;)J",
          "onSemaphoreAcquireUninterruptibly" to "(Ljava/util/concurrent/Semaphore;)V",
          "onSemaphoreAcquireDone" to "()V",
          "onSemaphoreReleasePermits" to "(Ljava/util/concurrent/Semaphore;I)V",
          "onSemaphoreRelease" to "(Ljava/util/concurrent/Semaphore;)V",
          "onSemaphoreReleaseDone" to "()V",
          "onSemaphoreDrainPermitsDone" to "()V",
          "onSemaphoreReducePermits" to "(Ljava/util/concurrent/Semaphore;I)V",
          "onSemaphoreReducePermitsDone" to "()V",
          "onSemaphoreDrainPermits" to "(Ljava/util/concurrent/Semaphore;)V",
          "onLatchAwait" to "(Ljava/util/concurrent/CountDownLatch;)V",
          "onLatchAwaitTimeout" to
              "(Ljava/util/concurrent/CountDownLatch;JLjava/util/concurrent/TimeUnit;)Z",
          "onLatchAwaitDone" to "(Ljava/util/concurrent/CountDownLatch;)V",
          "onLatchCountDown" to "(Ljava/util/concurrent/CountDownLatch;)V",
          "onLatchCountDownDone" to "(Ljava/util/concurrent/CountDownLatch;)V",
          "onReportError" to "(Ljava/lang/Throwable;)V",
          "onSemaphoreAcquirePermitsUninterruptibly" to "(Ljava/util/concurrent/Semaphore;I)V",
          "onLockLockInterruptibly" to "(Ljava/util/concurrent/locks/Lock;)V",
          "onUnsafeReadVolatile" to "(Ljava/lang/Object;J)V",
          "onUnsafeWriteVolatile" to "(Ljava/lang/Object;J)V",
          "onThreadParkNanos" to "(J)V",
          "onThreadParkUntil" to "(J)V",
          "onThreadParkNanosWithBlocker" to "(Ljava/lang/Object;J)V",
          "onThreadParkUntilWithBlocker" to "(Ljava/lang/Object;J)V",
          "onConditionAwaitNanos" to "(Ljava/util/concurrent/locks/Condition;J)J",
          "onConditionAwaitTime" to
              "(Ljava/util/concurrent/locks/Condition;JLjava/util/concurrent/TimeUnit;)Z",
          "onConditionAwaitUntil" to "(Ljava/util/concurrent/locks/Condition;Ljava/util/Date;)Z",
          "onConditionAwaitUninterruptibly" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onConditionAwaitUninterruptiblyDone" to "(Ljava/util/concurrent/locks/Condition;)V",
          "onThreadIsInterrupted" to "(ZLjava/lang/Thread;)Z",
          "onLockHasQueuedThreads" to "(ZLjava/util/concurrent/locks/Lock;)Z",
          "onLockHasQueuedThread" to "(ZLjava/util/concurrent/locks/Lock;Ljava/lang/Thread;)Z",
          "onNanoTime" to "()J",
          "onCurrentTimeMillis" to "()J",
          "onInstantNow" to "()Ljava/time/Instant;",
          "onObjectHashCode" to "(Ljava/lang/Object;)I",
          "onForkJoinPoolCommonPool" to
              "(Ljava/util/concurrent/ForkJoinPool;)Ljava/util/concurrent/ForkJoinPool;",
          "onThreadLocalRandomGetProbe" to "(I)I",
          "onThreadSleepMillis" to "(J)V",
          "onThreadSleepDuration" to "(Ljava/time/Duration;)V",
          "onThreadSleepMillisNanos" to "(JI)V",
          "onStampedLockReadLock" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockSkipDone" to "()V",
          "onStampedLockWriteLock" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockReadLockInterruptibly" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockWriteLockInterruptibly" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockReadLockTryLock" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockWriteLockTryLock" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockReadLockTryLockTimeout" to
              "(Ljava/util/concurrent/locks/StampedLock;JLjava/util/concurrent/TimeUnit;)J",
          "onStampedLockWriteLockTryLockTimeout" to
              "(Ljava/util/concurrent/locks/StampedLock;JLjava/util/concurrent/TimeUnit;)J",
          "onStampedLockUnlockReadDone" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockUnlockWriteDone" to "(Ljava/util/concurrent/locks/StampedLock;)V",
          "onStampedLockTryConvertToReadLockDone" to
              "(JLjava/util/concurrent/locks/StampedLock;J)J",
          "onStampedLockTryConvertToWriteLockDone" to
              "(JLjava/util/concurrent/locks/StampedLock;J)J",
          "onStampedLockTryConvertToOptimisticReadLockDone" to
              "(JLjava/util/concurrent/locks/StampedLock;J)J",
          "onStampedLockTryUnlockWriteDone" to "(ZLjava/util/concurrent/locks/StampedLock;)Z",
          "onStampedLockTryUnlockReadDone" to "(ZLjava/util/concurrent/locks/StampedLock;)Z",
          "onStampedLockSkip" to "()V",
          "onRangerCondition" to "(Lorg/pastalab/fray/runtime/RangerCondition;)V",
          "onSelectorOpen" to "()V",
          "onSelectorOpenDone" to "()V",
          "onSelectorSelect" to "(Ljava/nio/channels/Selector;)V",
          "onSelectorClose" to "(Ljava/nio/channels/Selector;)V",
          "onSelectorCloseDone" to "(Ljava/nio/channels/Selector;)V",
          "onServerSocketChannelBindDone" to "(Ljava/nio/channels/ServerSocketChannel;)V",
          "onServerSocketChannelAccept" to "(Ljava/nio/channels/ServerSocketChannel;)V",
          "onSocketChannelConnect" to
              "(Ljava/nio/channels/SocketChannel;Ljava/net/SocketAddress;)V",
          "onSelectorSetEventOpsDone" to
              "(Ljava/nio/channels/Selector;Ljava/nio/channels/SelectionKey;)V",
          "onSelectorCancelKeyDone" to
              "(Ljava/nio/channels/Selector;Ljava/nio/channels/SelectionKey;)V",
          "onSelectorSelectDone" to "(Ljava/nio/channels/Selector;)V",
          "onServerSocketChannelAcceptDone" to
              "(Ljava/nio/channels/ServerSocketChannel;Ljava/nio/channels/SocketChannel;)V",
          "onSocketChannelClose" to "(Ljava/nio/channels/spi/AbstractInterruptibleChannel;)V",
          "onSocketChannelCloseDone" to "(Ljava/nio/channels/spi/AbstractInterruptibleChannel;)V",
          "onSocketChannelConnectDone" to "(Ljava/nio/channels/SocketChannel;Z)V",
          "onSocketChannelFinishConnectDone" to "(Ljava/nio/channels/SocketChannel;Z)V",
          "onSocketChannelFinishConnect" to "(Ljava/nio/channels/SocketChannel;)V",
          "onSocketChannelRead" to "(Ljava/nio/channels/SocketChannel;)V",
          "onSocketChannelReadDoneInt" to "(ILjava/nio/channels/SocketChannel;)V",
          "onSocketChannelReadDone" to "(JLjava/nio/channels/SocketChannel;)V",
          "onSocketChannelWriteDoneInt" to "(ILjava/nio/channels/SocketChannel;)V",
          "onSocketChannelWriteDone" to "(JLjava/nio/channels/SocketChannel;)V",
          "onNioSocketConnect" to "(Ljava/net/SocketImpl;)V",
          "onNioSocketConnectDone" to "(Ljava/net/SocketImpl;)V",
          "onNioSocketRead" to "(Ljava/net/SocketImpl;)V",
          "onNioSocketReadDone" to "(Ljava/net/SocketImpl;I)V",
          "onNioSocketAccept" to "(Ljava/net/SocketImpl;)V",
          "onNioSocketAcceptDone" to "(Ljava/net/SocketImpl;)V")
}
